<?php

namespace Modules\Property\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\AdminController;
use Modules\Core\Models\Attributes;
use Modules\Property\Models\PropertyDokan;
use Modules\Property\Models\PropertyDokanTerm;
use Modules\Property\Models\PropertyDokanTranslation;
use Modules\Location\Models\Location;
use Modules\Property\Models\Property;
use Modules\Property\Models\PropertyTerm;
use Modules\Property\Models\PropertyTranslation;
use Modules\Location\Models\LocationCategory;

class DokanController extends AdminController
{
    protected $propertyClass;
    protected $dokanTermClass;
    protected $attributesClass;
    protected $location;
    /**
     * @var PropertyDokan
     */
    protected $dokanClass;
    protected $currentProperty;
    protected $dokanTranslationClass;

    public function __construct()
    {
        parent::__construct();
        $this->setActiveMenu(route('property.admin.index'));
        $this->propertyClass = Property::class;
        $this->dokanTermClass = PropertyDokanTerm::class;
        $this->attributesClass = Attributes::class;
        $this->location = Location::class;
        $this->dokanClass = PropertyDokan::class;
        $this->dokanTranslationClass = PropertyDokanTranslation::class;
        $this->locationCategoryClass = LocationCategory::class;
    }
    public function callAction($method, $parameters)
    {
        if (!Property::isEnable()) {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    protected function hasPropertyPermission($property_id = false)
    {
        if (empty($property_id)) return false;

        $property = $this->propertyClass::find($property_id);
        if (empty($property)) return false;

        if (!$this->hasPermission('property_manage_others') and $property->create_user != Auth::id()) {
            return false;
        }

        $this->currentProperty = $property;
        return true;
    }
    public function index(Request $request, $property_id)
    {
        $this->checkPermission('property_view');

        if (!$this->hasPropertyPermission($property_id)) {
            abort(403);
        }

        $query = $this->dokanClass::query();

        $query->orderBy('id', 'desc');
        if (!empty($property_name = $request->input('s'))) {
            $query->where('title', 'LIKE', '%' . $property_name . '%');
            $query->orderBy('title', 'asc');
        }

        $query->where('parent_id', $property_id);
        $data = [
            'rows'               => $query->with(['author'])->paginate(20),
            'property_manage_others' => $this->hasPermission('property_manage_others'),
            'breadcrumbs'        => [
                [
                    'name' => __('Properties'),
                    'url'  => route('property.admin.index')
                ],
                [
                    'name' => __('Property: :name', ['name' => $this->currentProperty->title]),
                    'url'  => route('property.admin.edit', ['id' => $this->currentProperty->id])
                ],
                [
                    'name'  => __('Dokan Management'),
                    'class' => 'active'
                ],
            ],
            'page_title' => __("Dokan Management"),
            'property' => $this->currentProperty,
            'row' => new $this->dokanClass(),
            'translation' => new $this->dokanTranslationClass(),
            'property_location' => $this->location::where('status', 'publish')->get(),
            'location_category' => $this->locationCategoryClass::where('status', 'publish')->get(),
            'attributes'     => $this->attributesClass::where('service', 'dokan')->get(),
        ];
        return view('Property::admin.dokan.index', $data);
    }

    public function edit(Request $request, $property_id, $id)
    {
        $this->checkPermission('property_update');

        if (!$this->hasPropertyPermission($property_id)) {
            abort(403);
        }

        $row = $this->dokanClass::find($id);
        if (empty($row) or $row->parent_id != $property_id) {
            return redirect(route('property.admin.dokan.index', ['property_id' => $property_id]));
        }

        $translation = $row->translateOrOrigin($request->query('lang'));
        if (!$this->hasPermission('property_manage_others')) {
            if ($row->create_user != Auth::id()) {
                return redirect(route('property.admin.dokan.index'));
            }
        }
        $data = [
            'row'            => $row,
            'translation'    => $translation,
            'property_location' => $this->location::where('status', 'publish')->get(),
            'location_category' => $this->locationCategoryClass::where('status', 'publish')->get(),
            "selected_terms" => $row->terms->pluck('term_id'),
            'attributes'     => $this->attributesClass::where('service', 'dokan')->get(),
            'enable_multi_lang' => true,
            'breadcrumbs'    => [
                [
                    'name' => __('Properties'),
                    'url'  => route('property.admin.index')
                ],
                [
                    'name' => __('Property: :name', ['name' => $this->currentProperty->title]),
                    'url'  => route('property.admin.edit', ['id' => $this->currentProperty->id])
                ],
                [
                    'name' => __('All Dokans'),
                    'url'  => route('property.admin.dokan.index', ['property_id' => $this->currentProperty->id])
                ],
                [
                    'name' => __('Edit dokan: :name', ['name' => $row->title]),
                ],
            ],
            'page_title' => __("Edit: :name", ['name' => $row->title]),
            'property' => $this->currentProperty
        ];
        return view('Property::admin.dokan.detail', $data);
    }

    public function store(Request $request, $property_id, $id)
    {

        if (!$this->hasPropertyPermission($property_id)) {
            abort(403);
        }
        if ($id > 0) {
            $this->checkPermission('property_update');
            $row = $this->dokanClass::find($id);
            if (empty($row)) {
                return redirect(route('property.admin.index'));
            }

            if ($row->create_user != Auth::id() and !$this->hasPermission('property_manage_others')) {
                return redirect(route('property.admin.dokan.index'));
            }

            if ($row->parent_id != $property_id) {
                return redirect(route('property.admin.dokan.index'));
            }
        } else {
            $this->checkPermission('property_create');
            $row = new $this->dokanClass();
            $row->status = "publish";
        }
        $dataKeys = [
            'title',
            'slug',
            'content',
            'business_type',
            'image_id',
            'banner_image_id',
            'person_profile_id',
            'video',
            'gallery',
            'location_id',
            'address',
            'map_lat',
            'map_lng',
            'map_zoom',
            'price',
            'number',
            'beds',
            'size',
            'adults',
            'children',
            'status',
            'email',
            'website',
            'contact_person',
            'phone',
            'contact_phone',
            'contact_whatsapp',
            'enable_open_hours',
            'open_hours',
            'products',
            'socials',
        ];

        $row->fillByAttr($dataKeys, $request->input());
        $row->ical_import_url  = $request->ical_import_url;

        if ($id < 0) {
            $row->parent_id = $property_id;
        }

        $res = $row->saveOriginOrTranslation($request->input('lang'), true);

        if ($res) {
            if (!$request->input('lang') or is_default_lang($request->input('lang'))) {
                $this->saveTerms($row, $request);
            }

            if ($id > 0) {
                return redirect()->back()->with('success',  __('Dokan updated'));
            } else {
                return redirect()->back()->with('success',  __('Dokan created'));
            }
        }
    }

    public function saveTerms($row, $request)
    {
        $this->checkPermission('property_manage_attributes');
        if (empty($request->input('terms'))) {
            $this->dokanTermClass::where('target_id', $row->id)->delete();
        } else {
            $term_ids = $request->input('terms');
            foreach ($term_ids as $term_id) {
                $this->dokanTermClass::firstOrCreate([
                    'term_id' => $term_id,
                    'target_id' => $row->id
                ]);
            }
            $this->dokanTermClass::where('target_id', $row->id)->whereNotIn('term_id', $term_ids)->delete();
        }
    }

    public function bulkEdit(Request $request)
    {
        $ids = $request->input('ids');
        $action = $request->input('action');
        if (empty($ids) or !is_array($ids)) {
            return redirect()->back()->with('error', __('No items selected!'));
        }
        if (empty($action)) {
            return redirect()->back()->with('error', __('Please select an action!'));
        }
        switch ($action) {
            case "delete":
                foreach ($ids as $id) {
                    $query = $this->dokanClass::where("id", $id);
                    $query->first();
                    if (!empty($query)) {
                        $query->delete();
                    }
                }
                return redirect()->back()->with('success', __('Deleted success!'));
                break;
            case "clone":
                $this->checkPermission('property_create');
                foreach ($ids as $id) {
                    (new $this->dokanClass())->saveCloneByID($id);
                }
                return redirect()->back()->with('success', __('Clone success!'));
                break;
            default:
                // Change status
                foreach ($ids as $id) {
                    $query = $this->dokanClass::where("id", $id);
                    if (!$this->hasPermission('property_manage_others')) {
                        $query->where("create_user", Auth::id());
                        $this->checkPermission('property_update');
                    }
                    $query->update(['status' => $action]);
                }
                return redirect()->back()->with('success', __('Update success!'));
                break;
        }
    }
}
